# Book settings
title: From Excel to Pandas
author: The Aiola Team
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

execute:
  timeout: 600

# Information about where the book exists on the web
repository:
  url : https://github.com/aiola-lab/from-excel-to-pandas  
